# Generated by Django 3.1.4 on 2022-03-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20220228_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sessiontermmodel',
            name='term_end_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontermmodel',
            name='term_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_start_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Students_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadamic_years', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schclass')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadamic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schclass')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadamic_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.terms')),
                ('acadamic_years', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SchClass_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schclass')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subjects')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='term_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sessionterm'),
        ),
    ]
