# Generated by Django 3.1.4 on 2022-03-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20220303_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='term_year_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sessionterm'),
        ),
    ]
