# Generated by Django 3.1.4 on 2022-04-13 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20220320_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_subject_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], max_length=10, null=True)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.schclass')),
                ('session_year_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sessionyearmodel')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.students')),
            ],
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='class_id',
        ),
        migrations.AddField(
            model_name='staff_class',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Unassigned', 'Unassigned')], default='Assigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='term_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.sessionterm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schclass_subjects',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schclass'),
        ),
        migrations.CreateModel(
            name='Daily_Subject_report_uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[534, 380], upload_to='')),
                ('report_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.daily_subject_report')),
            ],
        ),
        migrations.AddField(
            model_name='daily_subject_report',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.subjects'),
        ),
        migrations.AddField(
            model_name='daily_subject_report',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staffs'),
        ),
        migrations.AddField(
            model_name='daily_subject_report',
            name='term_year_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sessionterm'),
        ),
    ]
