# Generated by Django 3.1.4 on 2022-04-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20220413_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms_errormesseage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('event_time', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('recepient', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sms_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_date', models.DateField(auto_now_add=True)),
                ('sms', models.CharField(max_length=1000)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('event_time', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
