# Generated by Django 3.1.4 on 2022-04-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_sms_errormesseage_sms_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schclass'),
        ),
        migrations.AlterField(
            model_name='students_class',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schclass'),
        ),
        migrations.AlterField(
            model_name='students_class',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.students'),
        ),
    ]
