# Generated by Django 3.1.4 on 2022-04-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_auto_20220419_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostorder_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.hostorder'),
        ),
    ]
