# Generated by Django 3.1.4 on 2022-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auto_20220422_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostorder',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
