# Generated by Django 3.1.4 on 2022-04-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220401_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='arevenue',
            name='status',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Momo', 'Momo')], default='Cash', max_length=10),
        ),
    ]
