# Generated by Django 3.1.4 on 2022-04-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_arevenue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees_transaction',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='fees_transaction',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalfees_transaction',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='historicalfees_transaction',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalschool_bank_payments',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='historicalschool_bank_payments',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='school_bank_payments',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='school_bank_payments',
            name='phone',
        ),
    ]
