# Generated by Django 3.1.4 on 2022-04-13 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20220404_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv_payment_history',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phiscreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pv_payment_history',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phismodifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trrcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trrmodifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
