# Generated by Django 3.1.4 on 2022-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220413_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='arevenue',
            name='close',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='Old', max_length=10),
        ),
    ]
