# Generated by Django 3.1.4 on 2022-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_arevenue_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='tran_dec',
            field=models.CharField(blank=True, default='Transfer', max_length=300, null=True),
        ),
    ]
