# Generated by Django 3.1.4 on 2022-06-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0023_auto_20220609_1626'),
        ('accounts', '0010_transfers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arevenue',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.usershift'),
        ),
        migrations.AlterField(
            model_name='arevenue',
            name='status',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Momo', 'Momo'), ('Jumia', 'Jumia')], default='Cash', max_length=10),
        ),
    ]
