# Generated by Django 3.1.4 on 2022-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220614_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsub_accounts',
            name='tag',
            field=models.CharField(choices=[('Mulan', 'Mulan'), ('Partytree', 'Partytree'), ('Mulan Construct', 'Mulan Construct')], default='Mulan', max_length=20),
        ),
        migrations.AlterField(
            model_name='sub_accounts',
            name='tag',
            field=models.CharField(choices=[('Mulan', 'Mulan'), ('Partytree', 'Partytree'), ('Mulan Construct', 'Mulan Construct')], default='Mulan', max_length=20),
        ),
    ]
