# Generated by Django 3.1.4 on 2022-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0021_alter_snacks_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BClosing_Stock_summery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(auto_now_add=True, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('closing_stock_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BOpening_Stock_summery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(auto_now_add=True, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('closing_stock_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
