# Generated by Django 3.1.4 on 2022-06-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0024_auto_20220620_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershift',
            name='status_checking',
            field=models.BooleanField(default=True),
        ),
    ]
