# Generated by Django 3.1.4 on 2022-01-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partytree', '0002_auto_20210806_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='order_detailss',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partytree.orders'),
        ),
        migrations.AlterField(
            model_name='order_detailss',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partytree.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gross_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
