# Generated by Django 3.1.4 on 2022-04-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partytree', '0005_closing_stock_summery_opening_stock_summery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagess',
            name='created',
        ),
        migrations.RemoveField(
            model_name='damagess',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='damagess',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='damagess',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='HistoricalDamagess',
        ),
    ]
