# Generated by Django 3.1.4 on 2022-05-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partytree', '0006_auto_20220401_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
